package firemerald.mcms.util;

public interface Textures
{
	public static final String
		BOX = "box.png",
		EDITABLE_ADD_BONE = "editables/add_bone.png",
		EDITABLE_ADD_BOX = "editables/add_box.png",
		EDITABLE_ADD_MESH = "editables/add_mesh.png",
		EDITABLE_ADD_FRAME = "editables/add_frame.png",
		EDITABLE_COPY = "editables/copy.png",
		EDITABLE_MOVE_FRAME = "editables/move_frame.png",
		EDITABLE_DELETE = "editables/delete.png",
		MODEL_VISIBLE = "model/visible.png",
		MODEL_HIDDEN = "model/hidden.png",
		MODEL_EXPAND = "model/expand.png",
		MODEL_RETRACT = "model/retract.png",
		MODEL_ICON_BOX = "model/box.png",
		MODEL_ICON_MESH = "model/mesh.png",
		MODEL_ICON_BONE = "model/bone.png",
		ITEM_NEW = "items/new.png",
		ITEM_ADD = "items/add.png",
		ITEM_LOAD = "items/load.png",
		ITEM_COPY = "items/copy.png",
		ITEM_SAVE = "items/save.png",
		ITEM_EDIT = "items/edit.png",
		ITEM_REVERSE = "items/reverse.png",
		ITEM_REMOVE = "items/remove.png",
		ITEM_BROWSE = "items/browse.png",
		PLAYBACK_START = "playback/start.png",
		PLAYBACK_REVERSE = "playback/reverse.png",
		PLAYBACK_PAUSE = "playback/pause.png",
		PLAYBACK_FORWARD = "playback/forward.png",
		PLAYBACK_END = "playback/end.png",
		TOOL_MODEL = "tools/model.png",
		TOOL_PENCIL = "tools/pencil.png",
		TOOL_DROPPER = "tools/dropper.png",
		COLOR_DEFAULT = "tools/color_default.png",
		COLOR_SWAP = "tools/color_swap.png";
}